
    <a href="https://g03-appliedwebproject.atlassian.net/jira/software/projects/SCRUM/boards/1">
        <img src="styles/images/atlassian_jira_logo_icon_170511.webp" alt="">Jira Project</a>
    <a href="https://github.com/LeafMeAloneDawg/AppliedWebProject">
        <img src="styles/images/github-logo.png" alt="">GitHub Link</a>
    <a href="mailto:info@mysn.org.au">
        <img src="styles/images/email_logo.jpg" alt="">Email Us</a>
