<header>
        <!-- navigation bar -->
        <nav aria-label="Primary">
            <a href="index.html" class="nav_logo">
                <img src="styles/images/grp_3.png" alt="Melbourne Youth Support Network Logo"
                    title="Melbourne Youth Support Network">
            </a>

            <ul class="nav_links">
                <li><a href="index.html" aria-current="page">Home</a></li>
                <li><a href="jobs.html">Jobs</a></li>
                <li><a href="apply.html">Apply</a></li>
                <li><a href="about.html">About</a></li>
            </ul>
        </nav>

        <!-- Company logo / banner with text on top -->
        <div id="index_banner">
                <img src="styles/images/grp_3.png" id="company_logo" alt="Company Logo">
                <h1 id="index_logo_text_overlay">Melbourne Youth <br> Support Network</h1>
        </div>

    </header>