<!-- navigation bar -->
<nav aria-label="Primary">
    <a href="index.html" class="nav_logo">
        <img src="styles/images/grp_3.png" alt="Melbourne Youth Support Network Logo"
            title="Melbourne Youth Support Network">
    </a>
    <ul class="nav_links">
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About</a></li>
    </ul>
</nav>