<!-- navigation bar -->
<nav aria-label="Primary">
    <a href="index.html" class="nav_logo">
        <img src="styles/images/grp_3.png" alt="Melbourne Youth Support Network Logo"
            title="Melbourne Youth Support Network">
    </a>

    <ul class="nav_links">
        <li><a href="index.php" aria-current="page">Home</a></li>
        <li><a href="jobs.html">Jobs</a></li>
        <li><a href="apply.html">Apply</a></li>
        <li><a href="about.php">About</a></li>
    </ul>
</nav>